-- VIEWING THE TRIGGERS

-- UNFORTUNATELY WE CAN NOT VIEW THE TRIGGERS CREATED IN MYSQL WORKBENCH
-- WE CAN SEE TRIGGERS FOLLOWING WAY

SHOW TRIGGERS; -- IT WILL SHOW ALL THE TRIGGERS CREATED

-- WE CAN SEE THE TABLE SPECIFIC TRIGGERS IN FOLLOWING WAY

SHOW TRIGGERS LIKE 'payments%' -- if you follow the convention talked about earlier