-- VIEWING, DROPPING, ALTERING EVENTS 

-- viewing events

SHOW EVENTS; -- IT SHOWS ALL THE EVENTS AND THEIR CHARACTERISTICS

-- AS TOLD EARLIER IT IS GOOD PRACTICE TO NAME YOUR EVENTS BEGIN WITH THE INTERVAL LIKE YEARLY
-- SO THAT WE CAN FIND THEM USING LIKE OPERATOR

SHOW EVENTS LIKE 'year%';

-- DROP EVENTS
DROP EVENT IF EXISTS yearly_delete_stale_audit_rows; 

-- TO MAKE CHANGES TO EVENTS OR ALTERING THE EVENTS
-- SYNTEX IS SAME AS CREATING EVENTS BUT WE USE ALTER EVENTS

DELIMITER $$

ALTER EVENT yearly_delete_stale_audit_rows
ON SCHEDULE
EVERY 1 YEAR STARTS '2019-01-01' ENDS '2029-01-01' -- > we can change the interval
DO BEGIN
	-- > or we can change the body 
END$$
DELIMITER ;

-- WE CAN USE ALTER EVENT TO TEMPORARILY ENABLE OR DISABLE AN EVENT LIKE THIS:

ALTER EVENT yearly_delete_stale_audit_rows DISABLE;

-- OR WE CAN COME BACK LATER AND ENABLE LATER LIKE THIS:
ALTER EVENT yearly_delete_stale_audit_rows ENABLE;