-- NUMERIC FUNCTIONS

-- ROUND()

SELECT ROUND(5.73);
			-- WE CAN PASS PRECISION IN THE ROUND()
SELECT ROUND(5.735,1); -- IT WILL GIVE 5.7, ONE DIGIT AFTER DECIMAL POINT

-- TRUNCATE 

SELECT TRUNCATE(5.456002, 2);  -- REMOVING DIGITS AFTER 2 DECIMAL POINTS

-- CEILING()

SELECT CEILING(5.2); -- IT WILL RETURN THE ROUND WHICH IS HIGHER , IN THIS eg IT WILL RETURN TO 6

-- FLOOR()

SELECT FLOOR(5.9); -- IT WILL RETURN ROUND WHICH IS LOWER , IN THIS eg IT WILL RETURN TO 5

-- ABS()      TO CALCULATE THE ABSOLUTE value

SELECT ABS(5.2); -- WE GET THE ABSOLUTE VALUE, IF WE PUT (-5.2) IT WILL RETURN 5.2

-- RAND()  FOR GENERATING RANDOM FLOATING POINT NO BETWEEN 0 AND 1

SELECT RAND()

-- SEARCH FOR MYSQL NUMERIC FUNCTIONS IN THE GOOGLE

