-- STRING FUNCTIONS

-- LENGTH() 

SELECT LENGTH('SKY'); -- IT WILL RETURN THE LEN OF THE STRING, IN THIS eg IT WILL RETURN 3

-- UPPER()

SELECT UPPER('sky'); -- IT WILL RETURN THE UPPER CASE OF THE STRING, IN THIS EG IT WILL RETURN 'SKY'

SELECT LOWER('SKY'); -- IT WILL RETURN TO LOWER CASE , THESE FUNCTIONS ARE USED TO CONVERT THE VARIABLE INTO UPPER AND LOWER CASE

-- WE HAVE 3 FUNCTIONS TO REMOVE THE SPACES IN THE STRINGS
-- THESE FUNCTIONS ARE PRETTY USEFUL WHEN THE DATA IS ENTERED BY THE USER
-- SOME PEOPLE USE SPACE UNNCESSARY BEFORE AND AFTER THE VALUE
-- WE CAN TRIM THE VALUE USING THESE FUNCTIONS

-- 1. LTRIM() -- IT WILL REMOVE THE SPACE BEFORE THE 

SELECT LTRIM('     Sky');

-- 2. RTRIM() 

SELECT RTRIM('SKY    ');

-- 3. TRIM() -- IT WILL REMOVE ALL THE LEADING OR TRAILING SPACES

SELECT TRIM('    SKY   ');


-- LEFT() -- IT WILL RETURN THE LEFT CHARACTER OF THE STRING, LEFT('STRING', ARGUMENT)

SELECT LEFT('KINDERGARTEN', 4); -- IT WILL RETURN THE FIRST 4 LEFT CHARACTERS OF THE STRING , Ie KIND

-- RIGHT() -- IT IS SIMILAR TO RIGHT, ONLY SUBJECT MATTER IS LAST SPECIFIED NO OF CHARACTERS

SELECT RIGHT('KINDERGARTEN', 5); -- IT WILL RETURN THE LAST 5 CHARACTERS, Ie ARTEN

-- SUBSTRING() -- IT WILL RETURN ANY PART OF THE STRING , SUBSTRING('STRING', START POSITION, NO OF CHAR AFTER START POS)

SELECT SUBSTRING('KINDERGARTEN', 7, 4); -- IT WILL RETURN 'GART' 
SELECT SUBSTRING('KINDERGARTEN', 3); -- THE SECOND ARGUMENT IS OPTIONAL, NO IT WILL CHAR AFTER 3RD character

-- LOCATE() -- TO SEARCH LOCATION OF A CHAR IN STRING, LOCATE('ARGUMENT', 'STRING')

SELECT LOCATE('N', 'KINDERGARTEN'); -- IT WILL GIVE POSITION NO OF FIRST OCCURANCE OF THE 'N'
SELECT LOCATE('GARTEN', 'KINDERGARTEN'); -- IT WILL RETURN START OF OCCURANCE OF 'GARTEN', ie 7

-- REPLACE() -- 1ST ARGUMENT IS STRING , 2ND ARGUMENT IS WHAT WE WANT TO REPLACE, WHAT WE WANT TO REPLACE WITH

SELECT REPLACE('KINDERGARTEN', 'GARTEN', 'GARDEN');

-- CONCAT() -- USED FOR CONCATINATING STRINGS

SELECT CONCAT('JOHN', ' ' ,'CENA');

-- EXERCISE

USE sql_store;

SELECT CONCAT(first_name, ' ', last_name) AS full_name
FROM customers;

-- search for mysql string functions