-- date function 
-- in this session we gonna look at the functions to work with date and time

-- NOW() -- TO GET THE CURRENT DATE AND TIME

SELECT NOW();

-- CURDATE() -- TO GET CURRENT DATE WITHOUT THE TIME

SELECT CURDATE();

-- CURTIME() -- TO GET THE CURRENT TIME WITHOUT THE DATE

SELECT CURTIME();

-- WE CAN EXTRACT PART OF THE DATE TIME

SELECT YEAR(NOW());
SELECT MONTH(NOW());
SELECT DAY(NOW());
SELECT HOUR(NOW());
SELECT MINUTE(NOW());
SELECT SECOND(NOW());
SELECT DAYNAME(NOW()); -- NAME OF THE WEEKDAY
SELECT MONTHNAME(NOW()); -- NAME OF THE MONTH
SELECT EXTRACT(DAY FROM NOW());
SELECT EXTRACT(YEAR FROM NOW());

-- EXERCISE: PREVIOUSLY WE USED FOLLOWING CODE TO GET THE ORDER PLACED IN THE CURRENT YEAR
			SELECT *
			FROM orders	
			WHERE order_date >= '2019-01-01';
-- HOWEVER THE ABOVE WAY IS UNRELIABLE WAY TO EXTRACT THE ORDERS PLACED IN A CURRENT YEAR
-- BEACUSE IN THE NEXT YEAR THIS QUERY WILL RETURN THE ORDER PLACED IN PREVIOUS YEAR AS WELL AS CURRENT YEAR
-- WRITE A QUERY TO RETURN THE ORDER PLACED THIS YEAR

USE sql_store;

SELECT *
FROM orders
WHERE YEAR(order_date) = EXTRACT(YEAR FROM NOW());
