-- FORMATTING DATES AND TIMES
-- WE HAVE SEEN THE DATE AS '2019-09-25' 'YEAR HYPHEN MONTH HYPHEN DATE' 
-- IT IS GOOD FOR US DEVELOPERS BUT MIGHT NOT BE IDEAL FOR OTHERS
-- SO WE HAVE FUNCTIONS TO FORMAT DATE IN A MORE USER FRIENDLY WAY

-- 1. DATE_FORMAT() , IT TAKES 2 ARGUMENTS 1- DATE VALUE 2- FORMAT STRING WHICH CONTAINS CODES FOR FORMATTING THE VARIOUS PART OF A DATE

SELECT DATE_FORMAT(NOW(), '%y'); -- %y (SMALL y) FOR 2 DIGIT YEAR
SELECT DATE_FORMAT(NOW(), '%Y'); -- %Y (CAPITAL Y) FOR 4 DIGIT YEAR
SELECT DATE_FORMAT(NOW(), '%m'); -- %m FOR 2 DIGIT MONTH
SELECT DATE_FORMAT(NOW(), '%M'); -- %M FOR NAME OF THE MONTH eg NOVEMBER
SELECT DATE_FORMAT(NOW(), '%d'); -- %d FOR DAY OF THE MONTH 
SELECT DATE_FORMAT(NOW(), '%D'); -- %D FOR DAY OF MONTH , 22ND 

SELECT DATE_FORMAT(NOW(), '%M %d, %Y'); -- November 22, 2021

-- search for mysql date format functions