-- calculating date and time

-- quite often we need to perform calculations in the dates and time
-- in this session we gonna look at these functions to perform calculations on dates and times

-- DATE_ADD() -- TO ADD VALUE TO DATE
-- eg WE ARE ADDING 1 DAY TO OUR DATETIME

SELECT DATE_ADD(NOW(), INTERVAL 1 DAY);
SELECT DATE_ADD(NOW(), INTERVAL 1 MONTH); -- IT WILL ADD A MONTH, WE CAN SIMILARLY ADD YEAR, HOUR,MINUTE, WEEK
SELECT DATE_ADD(NOW(), INTERVAL -1 YEAR); -- WE CAN PASS A NEGATIVE VALUE TO IT, IT WILL RETURN THE PREVIOUS YEAR IN THIS eg

-- DATE_SUB() -- TO SUBSTRACT DATE PART FROM THE DATE
SELECT DATE_SUB(NOW(), INTERVAL 1 YEAR);  -- IT WILL RETURN THE PREVIOUS YEAR

-- WE CAN ALSO CALCULATE THE DIFFERENCE BETWEEN TWO DATES

-- DATEDIFF()

SELECT DATEDIFF(NOW(), '2019-01-01');
SELECT DATEDIFF('2011-11-25', '2019-07-01');

